name: Build zig-omelet

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    container:
      image: duckdb-by-clang:latest
      options: |
        --network host
      # --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install build package
        run: |
          echo "> packages..."
          # brew install catch2
          # brew install duckdb
          brew install zeromq

      - name: Install zig latest
        uses: mlugg/setup-zig@v1
        with:
          use-cache: false
          
      - name: Run test
        run: |
          BREW_HOME=/home/linuxbrew/.linuxbrew/opt
          zig build test -D"duckdb_prefix=/home/linuxbrew/duckdb" -D"zmq_prefix=$BREW_HOME/zeromq" -D"catch2_prefix=/home/linuxbrew/catch2" --verbose
          # zig build -D"duckdb_prefix=/home/linuxbrew/duckdb/_install" -D"zmq_prefix=$BREW_HOME/zeromq" -D"catch2_prefix=/home/linuxbrew/catch2" --verbose
