name: Build zig-omelet

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    container:
      image: ktzalias/omelet-actions-container:latest
      # options: |
      #   --network host
      # --privileged
      env:
        PKG_PREFIX: "/home/node"
        LD_LIBRARY_PATH: "/home/node/libsodium/lib:$LD_LIBRARY_PATH"

    steps:
      - name: Install git
        id: install-git
        uses: jcwillox/install-tool-action@v1
        with:
          repo: "git/git"
          download_url: "/archive/refs/tags/v{{version}}.tar.gz"
          version: "2.46.0"

      - name: Check git
        run: |
          echo "path = ${{ steps.install-git.outputs.path }}"
          echo "versuion = ${{ steps.install-git.outputs.version }}"

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install zig latest
        uses: mlugg/setup-zig@v1
        with:
          use-cache: false
          
      - name: Run test
        run: |
          zig build test -D"duckdb_prefix=$PKG_PREFIX/duckdb" -D"zmq_prefix=$PKG_PREFIX/zeromq" -D"catch2_prefix=$PKG_PREFIX/catch2" --verbose
          # zig build -D"duckdb_prefix=/home/linuxbrew/duckdb/_install" -D"zmq_prefix=$BREW_HOME/zeromq" -D"catch2_prefix=/home/linuxbrew/catch2" --verbose
