name: Build zig-omelet

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    container:
      image: ktzalias/omelet-actions-container:latest
      env:
        PKG_PREFIX: "/home/node"
        LD_LIBRARY_PATH: "/home/node/libsodium/lib:$LD_LIBRARY_PATH"

    steps:
      - name: Install git
        run: |
          apt-get update
          apt-get install -y git xz-utils
      - name: Check git version
        run: |
          git --version

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install zig latest
        uses: mlugg/setup-zig@v1
        with:
          version: master
          use-cache: false
          
      - name: Run test
        run: |
          zig build test -D"duckdb_prefix=$PKG_PREFIX/duckdb" -D"zmq_prefix=$PKG_PREFIX/zeromq" -D"catch2_prefix=$PKG_PREFIX/catch2" --verbose
      - name: Run build
          zig build -D"duckdb_prefix=$PKG_PREFIX/duckdb/_install" -D"zmq_prefix=$PKG_PREFIX/zeromq" -D"catch2_prefix=$PKG_PREFIX/catch2" --verbose
