name: Build zig-omelet

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DUCKDB_VERSION: 1.5.4
  ZIG_VERSION: 0.16.0

jobs:
  prepare:
    uses: ./.github/workflows/prepare.yml
         
  build:
    needs: prepare
    if: needs.prepare.outputs.skip != 'true'

    runs-on: ubuntu-26.04

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install system packages
        run: |
          dpkg -l \
            libc6-dev \
            libstdc++-15-dev \
            libgcc-15-dev

          sudo apt-get update && sudo apt-get install -y \
            libnng-dev \
            libcatch2-dev \
      - name: Setup libnng & libcatch2
        run: |
          sudo mkdir -p /opt/deps/nng /opt/deps/catch2 && \
          sudo ln -sfn /usr/include /opt/deps/nng/include && \
          sudo ln -sfn /usr/lib/x86_64-linux-gnu /opt/deps/nng/lib && \
          sudo ln -sfn /usr/include /opt/deps/catch2/include && \
          sudo ln -sfn /usr/lib /opt/deps/catch2/lib
      - name: Install duckDB
        run: |
          curl -L https://install.duckdb.org/v${DUCKDB_VERSION}/libduckdb-linux-amd64.zip \
            -o /tmp/libduckdb.zip && \
            unzip /tmp/libduckdb.zip -d /tmp/libduckdb

          ls -l /tmp/libduckdb
          sudo mkdir -p /opt/deps/duckdb/lib
          sudo cp -v /tmp/libduckdb/* /opt/deps/duckdb/lib
          ls -l /opt/deps/duckdb/lib
      - name: Install DuckDB headers
        run: |
          rm -rf /tmp/duckdb-src

          git clone --depth=1 --branch v${DUCKDB_VERSION} https://github.com/duckdb/duckdb /tmp/duckdb-src && \
          sudo cp -R /tmp/duckdb-src/src/include /opt/deps/duckdb/include
      - name: Setup pkg prefix
        run: |
          echo "DUCKDB_PREFIX=/opt/deps/duckdb" >> $GITHUB_ENV
          echo "NNG_PREFIX=/opt/deps/nng" >> $GITHUB_ENV
          echo "CATCH2_PREFIX=/opt/deps/catch2" >> $GITHUB_ENV

      - name: Install Zig ${{ env.ZIG_VERSION }}
        uses: mlugg/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}
          use-cache: false
      - name: Show zig version
        run: zig version
          
      - name: Run test
        run: |
          zig build test-all -DSKIP_BUILDS="duckdb-extract" --verbose
